feat: add pmd
PreMiD/Documentation pull request #1006
Opened 2022-09-16 20:04 UTC by Timeraa

This PR updates the presence.md to reflect the upcoming changes for the new CLI `pmd`.

I have removed all the metadata.json explanation & example code, as there is a whole file dedicated to explaining it. Presence.ts example code alongside tsconfig has been removed as well, since those are automatically generated by pmd.

2022-09-16 20:07 UTC, EncryptedDev commented
Can't review until I see how the scrip actually works. You should create a video running through the features and usage etc

2022-09-16 20:33 UTC, Timeraa commented
![pmd](https://user-images.githubusercontent.com/29104008/190727956-193600c1-ac48-460a-9ad8-3696113a8444.gif)
@EncryptedDev

2022-09-17 22:25 UTC, EncryptedDev requested changes

2022-09-17 22:26 UTC, EncryptedDev approved these changes

2022-09-17 22:28 UTC, alexbcberio approved these changes

2022-09-17 22:28 UTC, merged