docs(Guidelines): update guidelines
PreMiD/Documentation pull request #767
Opened 2021-12-07 23:50 UTC by EncryptedDev

2021-12-07 23:55 UTC, ImRodry requested changes

2021-12-07 23:55 UTC, ImRodry commented on en/dev/presence/guidelines.md
> +- If the presence author hasn't made the required changes within a month, you may contact a reviewer to see if you can to modify the presence.
```suggestion
- If the presence author hasn't been contactable in over a month, you may contact a reviewer to see if you can modify the presence.
```

2021-12-08 00:14 UTC, ImRodry approved these changes

2021-12-08 01:07 UTC, Bas950 approved these changes

2021-12-08 01:08 UTC, merged